"""inital schema

Revision ID: 9d50198dd0ff
Revises: 
Create Date: 2026-09-28 12:03:04.156560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d50198dd0ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('product')
    op.drop_table('customer')
    op.drop_constraint(op.f('certifications_sid_fkey'), 'certifications', type_='foreignkey')
    op.create_foreign_key(None, 'certifications', 'students', ['sid'], ['sid'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_sid_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'students', ['sid'], ['sid'], ondelete='CASCADE')
    op.alter_column('resumes', 'file_data',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_constraint(op.f('resumes_sid_fkey'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'students', ['sid'], ['sid'], ondelete='CASCADE')
    op.drop_constraint(op.f('skills_sid_fkey'), 'skills', type_='foreignkey')
    op.create_foreign_key(None, 'skills', 'students', ['sid'], ['sid'], ondelete='CASCADE')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=10000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.create_foreign_key(op.f('skills_sid_fkey'), 'skills', 'students', ['sid'], ['sid'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_sid_fkey'), 'resumes', 'students', ['sid'], ['sid'])
    op.alter_column('resumes', 'file_data',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_sid_fkey'), 'projects', 'students', ['sid'], ['sid'])
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.create_foreign_key(op.f('certifications_sid_fkey'), 'certifications', 'students', ['sid'], ['sid'])
    op.create_table('customer',
    sa.Column('customerid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customername', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customerid', name=op.f('customer_pkey'))
    )
    op.create_table('product',
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productname', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('productid', name=op.f('product_pkey'))
    )
    op.create_table('orders',
    sa.Column('orderid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customerid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('productid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customerid'], ['customer.customerid'], name=op.f('orders_customerid_fkey')),
    sa.ForeignKeyConstraint(['productid'], ['product.productid'], name=op.f('orders_productid_fkey')),
    sa.PrimaryKeyConstraint('orderid', name=op.f('orders_pkey'))
    )
    # ### end Alembic commands ###
